module.exports.userController = require('./user')
module.exports.productController = require('./product')
module.exports.categoryController = require('./category')
module.exports.transactionController = require('./transaction')
module.exports.uberRUSHController = require('./uberRUSH')
module.exports.coinbaseController = require('./coinbase')